Update patch set 2
Patch Set 2:

Just got this on SM-G930F :

04-30 17:39:20.026 21115-21130/cx.ring D/libdring: pjsip version 2.6 for aarch64-unknown-linux-android initialized
    GNU TLS version 3.5.10 initialized
    [ice] added host stun server
    [ice] added host stun server
04-30 17:39:20.027 21115-21130/cx.ring D/libdring: Configuration file path: /data/user/0/cx.ring/app_config/dring.yml
04-30 17:39:20.125 21115-21130/cx.ring I/DaemonService: DaemonService started
04-30 17:39:20.127 21115-21130/cx.ring D/RingApplication: bootstrapDaemon: At least one camera available. Initializing video...
04-30 17:39:20.127 21115-21130/cx.ring I/cx.ring.services.HardwareServiceImpl: initVideo()
04-30 17:39:20.129 21115-21130/cx.ring D/cx.ring.services.HardwareService: addVideoDevice: 0
04-30 17:39:20.130 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: getCameraInfo: 0
04-30 17:39:20.380 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: getCameraInfo: using resolution 640x480 15 FPS
04-30 17:39:20.385 21115-21130/cx.ring D/libdring: AndroidVideo: picked format NV21
04-30 17:39:20.386 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: setParameters: 0, 17, 480, 640, 30
04-30 17:39:20.394 21115-21130/cx.ring D/cx.ring.services.HardwareService: addVideoDevice: 1
04-30 17:39:20.394 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: getCameraInfo: 1
04-30 17:39:20.571 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: getCameraInfo: using resolution 640x480 15 FPS
04-30 17:39:20.578 21115-21130/cx.ring D/libdring: AndroidVideo: picked format NV21
04-30 17:39:20.579 21115-21130/cx.ring D/cx.ring.services.HardwareServiceImpl: setParameters: 1, 17, 480, 640, 30
04-30 17:39:20.589 21115-21130/cx.ring D/cx.ring.services.HardwareService: setDefaultVideoDevice: 1
04-30 17:39:20.589 21115-21130/cx.ring D/libdring: Setting default device to 1
04-30 17:39:20.590 21115-21130/cx.ring D/libdring: Saving Configuration to XDG directory /data/user/0/cx.ring/app_config/dring.yml
04-30 17:39:20.596 21115-21130/cx.ring D/CallService: Muting. ringtone.
04-30 17:39:20.600 21115-21115/cx.ring D/CallService: Muting. ringtone.
04-30 17:39:20.606 21115-21155/cx.ring W/AccountService: refreshAccountsCacheFromDaemon
04-30 17:39:20.608 21115-21130/cx.ring I/AccountService: getAccountList() thread running...
04-30 17:39:20.609 21115-21155/cx.ring W/AccountService: refreshAccountsCacheFromDaemon: recycled 0
04-30 17:39:20.611 21115-21155/cx.ring W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Index: 0, Size: 0
04-30 17:39:20.612 21115-21155/cx.ring W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.operators.mixed.ObservableSwitchMapSingle$SwitchMapSingleMainObserver.drain(ObservableSwitchMapSingle.java:210)
        at io.reactivex.internal.operators.mixed.ObservableSwitchMapSingle$SwitchMapSingleMainObserver.onError(ObservableSwitchMapSingle.java:144)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
04-30 17:39:20.613 21115-21155/cx.ring W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:563)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:558)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:265)
        at cx.ring.services.AccountService.refreshAccountsCacheFromDaemon(AccountService.java:234)
        at cx.ring.services.AccountService.access$000(AccountService.java:92)
        at cx.ring.services.AccountService$1.run(AccountService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
04-30 17:39:20.614 21115-21155/cx.ring W/System.err: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at cx.ring.services.AccountService.lambda$new$0$AccountService(AccountService.java:125)
        at cx.ring.services.AccountService$$Lambda$0.apply(Unknown Source)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
    	... 12 more
04-30 17:39:20.615 21115-21155/cx.ring E/RingApplication: Uncaught Exception detected in thread 
    io.reactivex.exceptions.OnErrorNotImplementedException: Index: 0, Size: 0
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.operators.mixed.ObservableSwitchMapSingle$SwitchMapSingleMainObserver.drain(ObservableSwitchMapSingle.java:210)
        at io.reactivex.internal.operators.mixed.ObservableSwitchMapSingle$SwitchMapSingleMainObserver.onError(ObservableSwitchMapSingle.java:144)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:563)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:558)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:265)
        at cx.ring.services.AccountService.refreshAccountsCacheFromDaemon(AccountService.java:234)
        at cx.ring.services.AccountService.access$000(AccountService.java:92)
        at cx.ring.services.AccountService$1.run(AccountService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at cx.ring.services.AccountService.lambda$new$0$AccountService(AccountService.java:125)
        at cx.ring.services.AccountService$$Lambda$0.apply(Unknown Source)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:563) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:558) 
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:265) 
        at cx.ring.services.AccountService.refreshAccountsCacheFromDaemon(AccountService.java:234) 
        at cx.ring.services.AccountService.access$000(AccountService.java:92) 
        at cx.ring.services.AccountService$1.run(AccountService.java:176) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
04-30 17:39:20.615 21115-21155/cx.ring I/Process: Sending signal. PID: 21115 SIG: 9

Patch-set: 2
Reviewer: Gerrit User 567 <567@1e26b4c1-6b8c-47ff-9df7-501b633d3b5a>
Label: Code-Review=0