Update patch set 6
Patch Set 6:

Some resources seem missing.

Error:(292, 60) error: cannot find symbol variable dialog_account_import
Error:(293, 60) error: cannot find symbol variable pwd_txt

Patch-set: 6