Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 2: Code-Review-2
> > 
> > Crash when downloading file
> 
> done

Not sufficient.

`MimeTypeMap.getSingleton().getMimeTypeFromExtension(fileExtension.toLowerCase());` can be null :)


```
07-09 13:28:25.807 20102-20102/cx.ring E/RingApplication: Uncaught Exception detected in thread 
                                                          java.lang.IllegalArgumentException: mimeType can't be null
                                                              at android.app.DownloadManager.validateArgumentIsNonEmpty(DownloadManager.java:1542)
                                                              at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1500)
                                                              at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1449)
                                                              at cx.ring.fragments.ConversationFragment.displayCompletedDownload(ConversationFragment.java:686)
                                                              at cx.ring.conversation.ConversationPresenter.lambda$downloadFile$5$ConversationPresenter(ConversationPresenter.java:254)
                                                              at cx.ring.conversation.ConversationPresenter$$Lambda$10.accept(Unknown Source)
                                                              at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
                                                              at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
                                                              at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

Patch-set: 3