Update patch set 6
Patch Set 6: Code-Review-2

I am able to get this stack trace by manually going in Settings -> Apps -> Ring -> Permissions turn off Contacts permission and coming back to the app

java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{27eccda 6766:cx.ring/u0a65} (pid=6766, uid=10065) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
                                                        at android.os.Parcel.readException(Parcel.java:1599)
                                                        at android.os.Parcel.readException(Parcel.java:1552)
                                                        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
                                                        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
                                                        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
                                                        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
                                                        at android.content.ContentResolver.query(ContentResolver.java:475)
                                                        at android.content.ContentResolver.query(ContentResolver.java:434)
                                                        at cx.ring.model.CallContact.buildUserContact(CallContact.java:96)
                                                        at cx.ring.views.MenuHeaderView.initViews(MenuHeaderView.java:135)
                                                        at cx.ring.views.MenuHeaderView.<init>(MenuHeaderView.java:75)
                                                        at cx.ring.client.HomeActivity$7.onServiceConnected(HomeActivity.java:420)

Also, When turning on Ring -> Settings -> Allow system contacts, I accept the permission in the popup, go back to home screen, contacts are not loaded.
I have to force quit the app and relaunch.

Second point is more important, this is what the user will see. First point is actually acceptable because the exception is properly handled in the code (it's just ugly to see that in log)

Everything works fine for Audio permission. I'm checking for video

Patch-set: 6
Label: Code-Review=-2